# Generated by Django 6.0.5 on 2026-05-24 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('caratula', models.CharField(max_length=80)),
                ('fecha_inicio', models.DateField()),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cedula', models.CharField(choices=[('ELECTRONICA', 'Electrónica'), ('PAPEL', 'Papel')], max_length=20)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cedulas', to='cedulas.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='Audiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=80)),
                ('resultado', models.CharField(max_length=80)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiencias', to='cedulas.expediente')),
            ],
        ),
    ]
