# Generated by Django 6.0.5 on 2026-05-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_expediente', models.CharField(max_length=20)),
                ('caratula', models.CharField(max_length=80)),
                ('tipo_cedula', models.CharField(choices=[('ELECTRONICA', 'Electrónica'), ('PAPEL', 'Papel')], max_length=20)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
