# Generated by Django 6.0.5 on 2026-05-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedulas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiencia',
            name='estado',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='resultado',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='tipo',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
