# Generated by Django 6.0.5 on 2026-05-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedulas', '0002_alter_audiencia_estado_alter_audiencia_resultado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedula',
            name='numero_cedula',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
