# Generated by Django 6.0.5 on 2026-05-30 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedulas', '0003_cedula_numero_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedula',
            name='notificoparte',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cedula',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cedulas.expediente'),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='numero_cedula',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
